name: EliAI
options:
  bundleIdPrefix: com.eliaigemini
  deploymentTarget:
    iOS: 17.0
targets:
  EliAI:
    type: application
    platform: iOS
    sources: [EliAI/EliAI]
    info:
      path: EliAI/EliAI/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchScreen: {}
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.eliaigemini.localai
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      INFOPLIST_FILE: EliAI/EliAI/Info.plist
      SWIFT_COMPILATION_MODE: wholemodule
      OTHER_SWIFT_FLAGS:
        - -cxx-interoperability-mode=default
    dependencies:
      - package: LLM
        product: LLM
      - package: SwiftMath
        product: SwiftMath
      - sdk: Accelerate.framework
    scheme:
      testTargets:
        - EliAITests
        - EliAIUITests
  EliAITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - EliAI/Tests/EliAITests
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: EliAI
  EliAIUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - EliAI/Tests/EliAIUITests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      TEST_TARGET_NAME: EliAI
    dependencies:
      - target: EliAI
packages:
  LLM:
    url: https://github.com/eastriverlee/LLM.swift.git
    revision: 4c4e909ac4758c628c9cd263a0c25b6edff5526d
  SwiftMath:
    url: https://github.com/mgriebling/SwiftMath.git
    revision: fa8244ed032f4a1ade4cb0571bf87d2f1a9fd2d7
